# Generated by Django 2.2.7 on 2020-01-04 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='weight',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='total_penalty',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Time_Penalty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_penalty', models.IntegerField(default=0)),
                ('no_wa', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Userdata')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main_app.Question')),
            ],
            options={
                'unique_together': {('player', 'question')},
            },
        ),
        migrations.AddField(
            model_name='question',
            name='time_penalty',
            field=models.ManyToManyField(blank=True, null=True, through='main_app.Time_Penalty', to='main_app.Userdata'),
        ),
    ]
