# Generated by Django 2.2.7 on 2020-01-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200104_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='weight',
            field=models.IntegerField(default=20),
        ),
    ]
