# Generated by Django 2.2.7 on 2020-01-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200104_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='chancesUsed',
            field=models.IntegerField(default=0),
        ),
    ]
