# Generated by Django 2.1.7 on 2021-03-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_userdata_chancesused'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='test_case4',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='question',
            name='test_case4_sol',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='question',
            name='test_case5',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='question',
            name='test_case5_sol',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='question',
            name='test_case6',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='question',
            name='test_case6_sol',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='question',
            name='test_case1',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='question',
            name='test_case1_sol',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='question',
            name='test_case2',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='question',
            name='test_case2_sol',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='question',
            name='test_case3',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='question',
            name='test_case3_sol',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
